### ISSUE TITLE
Add weapons and NPCs in the following modules

### ISSUE THREAD

**Issue by magisk6666** [TheWhiteAK/xashsandbox#1]
I hope to add more weapon NPCs to the version of the screen

Including the source code of the following initiator
**http://www.moddb.com/mods/zombie-x-10-final**

_http://www.moddb.com/mods/they-hunger_
[]()https://store.steampowered.com/app/10/CounterStrike/

**Comment by magisk6666** [comment]
http://www.moddb.com/mods/zombie-x-10-final

http://www.moddb.com/mods/they-hunger

https://store.steampowered.com/app/10/CounterStrike/

**Comment by Sergii03** [comment]
We add weapons and NPCs only from famous and legendary mods. Soon I will cut a lot of weapons and NPCs.
